{% set name = "scikit-posthocs" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ac6ebef9d019b1fd802c122b79bd0441f419ccd641a91eeb2c9b86c87ec79bd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python >=3.9
    - scipy >=1.9.0
    - seaborn
    - statsmodels

test:
  imports:
    - scikit_posthocs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/maximtrp/scikit-posthocs
  summary: Statistical post-hoc analysis and outlier detection algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maximtrp
