{% set name = "scikit-posthocs" %}
{% set version = "0.11.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ecb5a80bfecd38884f100c01dcfc1014ad4d6a0da9eeb779381782d9ea43311d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python >={{ python_min }}
    - scipy >=1.9.0
    - seaborn
    - statsmodels

test:
  imports:
    - scikit_posthocs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/maximtrp/scikit-posthocs
  summary: Statistical post-hoc analysis and outlier detection algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maximtrp
