{% set name = "scikit-posthocs" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-posthocs-{{ version }}.tar.gz
  sha256: 61a670d5ebcfb52e93beef0a8d7ff0260fd803d2e36fcd97492e64909890dd71

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python >=3.9
    - scipy >=1.9.0
    - seaborn
    - statsmodels

test:
  imports:
    - scikit_posthocs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/maximtrp/scikit-posthocs
  summary: Statistical post-hoc analysis and outlier detection algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maximtrp
